# Generated by Django 3.0.7 on 2020-06-29 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documental', '0015_auto_20200627_1015'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chequeo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verificado', models.BooleanField(default=False)),
                ('aplica', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ListaChequeo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(help_text='Área de la empresa donde se aplica el chequeo', max_length=255)),
                ('tipo_documento', models.CharField(default='PLANO', help_text='Tipos de documentos donde se aplica el check list', max_length=255)),
                ('nombre', models.CharField(help_text='Nombre de la lista de Verificación', max_length=255)),
                ('descripcion', models.CharField(help_text='Descripción detallada de la Lista de Verificación', max_length=1000, null=True, verbose_name='Descripción')),
            ],
            options={
                'ordering': ['area', 'tipo_documento', 'nombre'],
                'permissions': (('list_listas_chequeo', 'Can list Listas chequeo'),),
            },
        ),
        migrations.CreateModel(
            name='TipoChequeo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', help_text='Nombre de la Verificación a realizar', max_length=255)),
                ('ayuda', models.CharField(help_text='Descripción detallada de la Verificación', max_length=1000, null=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.AddIndex(
            model_name='tipochequeo',
            index=models.Index(fields=['nombre'], name='calidad_tip_nombre_f5fca6_idx'),
        ),
        migrations.AddField(
            model_name='listachequeo',
            name='tipos_chequeo',
            field=models.ManyToManyField(help_text='Verificación a realizar', related_name='tipos_chequeo', to='calidad.TipoChequeo'),
        ),
        migrations.AddField(
            model_name='chequeo',
            name='documento',
            field=models.ForeignKey(default=0, help_text='Documento al que pertenece el check', on_delete=django.db.models.deletion.CASCADE, related_name='documento', to='documental.Documento'),
        ),
        migrations.AddField(
            model_name='chequeo',
            name='tipo_chequeo',
            field=models.ForeignKey(help_text='Verificación a realiar', on_delete=django.db.models.deletion.DO_NOTHING, related_name='tipo_chequeo', to='calidad.TipoChequeo'),
        ),
        migrations.AddField(
            model_name='chequeo',
            name='verificado_por',
            field=models.ForeignKey(default=None, help_text='Persona que realizó la verificación', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='verificado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='listachequeo',
            index=models.Index(fields=['area', 'tipo_documento', 'nombre'], name='calidad_lis_area_8cb899_idx'),
        ),
    ]
