# Generated by Django 3.0.7 on 2020-06-29 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calidad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chequeo',
            name='aplica',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='chequeo',
            name='verificado',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='chequeo',
            name='verificado_por',
            field=models.ForeignKey(blank=True, default=None, help_text='Persona que realizó la verificación', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='verificado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listachequeo',
            name='tipos_chequeo',
            field=models.ManyToManyField(blank=True, help_text='Verificación a realizar', related_name='tipos_chequeo', to='calidad.TipoChequeo'),
        ),
    ]
