# Generated by Django 3.0.7 on 2020-06-29 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calidad', '0002_auto_20200629_1258'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listachequeo',
            options={'ordering': ['area', 'tipo_documento', 'nombre'], 'permissions': (('list_listaschequeo', 'Can list listas chequeo'),)},
        ),
        migrations.AlterField(
            model_name='chequeo',
            name='aplica',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='chequeo',
            name='verificado',
            field=models.BooleanField(default=False),
        ),
    ]
