# Generated by Django 3.0.7 on 2020-07-03 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calidad', '0004_auto_20200630_0954'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chequeo',
            options={'ordering': ['documento']},
        ),
        migrations.AlterField(
            model_name='chequeo',
            name='tipo_chequeo',
            field=models.ForeignKey(help_text='Verificación a realizar', on_delete=django.db.models.deletion.DO_NOTHING, related_name='tipo_chequeo', to='calidad.TipoChequeo'),
        ),
        migrations.AddIndex(
            model_name='chequeo',
            index=models.Index(fields=['documento'], name='calidad_che_documen_cc6197_idx'),
        ),
    ]
