# Generated by Django 3.0.7 on 2020-07-07 14:29

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('espacial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementoespacial',
            name='puntos',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
