# Generated by Django 3.0.7 on 2020-07-07 21:17

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espacial', '0002_auto_20200707_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elementoespacial',
            name='puntos',
        ),
        migrations.AddField(
            model_name='elementoespacial',
            name='atributo',
            field=models.CharField(help_text='Atributo del punto.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='elementoespacial',
            name='punto',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='elementoespacial',
            name='poligono',
            field=django.contrib.gis.db.models.fields.PolygonField(null=True, srid=4326),
        ),
    ]
