# Generated by Django 3.0.7 on 2020-07-10 20:04

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('espacial', '0003_auto_20200707_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementoespacial',
            name='linea',
            field=django.contrib.gis.db.models.fields.LineStringField(null=True, srid=4326),
        ),
    ]
