# Generated by Django 3.0.7 on 2020-07-10 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espacial', '0004_elementoespacial_linea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementoespacial',
            name='tipo_elemento',
            field=models.CharField(choices=[('PT', 'Puntos'), ('PL', 'Poligono'), ('LN', 'Linea')], default='PL', max_length=2),
        ),
    ]
