# Generated by Django 3.0.7 on 2020-07-29 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MansajeDestinatarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leido', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.CharField(help_text='Mensaje', max_length=1000)),
                ('fecha', models.DateField(default=django.utils.timezone.now, help_text='Fecha del mensaje')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Tique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(help_text='Mensaje', max_length=1000)),
                ('tipo_tique', models.CharField(choices=[('OBS', 'Observación'), ('REV', 'Revisión')], default='OBS', help_text='Tipo corrección aplicable al Tique', max_length=3)),
                ('finalizado', models.BooleanField(null=True)),
                ('fecha_emision', models.DateField(default=django.utils.timezone.now, help_text='Fecha de emisión del tique')),
                ('fecha_adquisicion', models.DateField(help_text='Fecha en la que el usaurio acepta el tique', null=True)),
                ('fecha_finalización', models.DateField(help_text='Fecha en la que el usaurio finaliza el tique', null=True)),
                ('propietario', models.ForeignKey(help_text='Miembro del equipo de trabajo responsable de las correcciones', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.CreateModel(
            name='TiqueDestinatarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miembro', models.ForeignKey(help_text='Miembro del equipo de trabajo', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tique', models.ForeignKey(help_text='Tique', null=True, on_delete=django.db.models.deletion.SET_NULL, to='mensajes.Tique')),
            ],
        ),
        migrations.AddIndex(
            model_name='mensaje',
            index=models.Index(fields=['fecha'], name='mensajes_me_fecha_b842b5_idx'),
        ),
        migrations.AddField(
            model_name='mansajedestinatarios',
            name='mensaje',
            field=models.ForeignKey(help_text='Mensaje', null=True, on_delete=django.db.models.deletion.SET_NULL, to='mensajes.Mensaje'),
        ),
        migrations.AddField(
            model_name='mansajedestinatarios',
            name='miembro',
            field=models.ForeignKey(help_text='Miembro del equipo de trabajo', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='tique',
            index=models.Index(fields=['fecha_emision'], name='mensajes_ti_fecha_e_876e80_idx'),
        ),
    ]
