# Generated by Django 3.0.7 on 2020-08-02 22:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mensajes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MansajeDestinatarios',
            new_name='MensajeDestinatarios',
        ),
        migrations.AlterField(
            model_name='tique',
            name='propietario',
            field=models.ForeignKey(help_text='Miembro del equipo de trabajo responsable de las correcciones', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propietario', to=settings.AUTH_USER_MODEL),
        ),
    ]
