# Generated by Django 3.0.7 on 2020-08-09 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajes', '0003_auto_20200802_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajedestinatarios',
            name='leido',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tique',
            name='finalizado',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
