# Generated by Django 3.0.7 on 2020-06-19 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(help_text='Nombre del archivo', max_length=255)),
                ('directorio', models.CharField(help_text='Directorio de almacenamiento del archivo', max_length=255)),
                ('tipo_representacion', models.CharField(help_text='Tipo de obra que representa el Documento (Civil, Mecánico, etc)', max_length=255, null=True, verbose_name='Tipo de representación')),
                ('revision', models.CharField(default='A', help_text='Revisión actual del archivo', max_length=3, verbose_name='Revisión')),
                ('descripcion', models.CharField(help_text='Breve descripción del archivo', max_length=1000, null=True, verbose_name='Descripción')),
                ('fecha_creacion', models.DateField(default=django.utils.timezone.now, help_text='Fecha de creación del archivo según el file system', verbose_name='Fecha creación')),
                ('fecha_edicion', models.DateField(default=django.utils.timezone.now, help_text='Fecha de edición del archivo según el file system', verbose_name='Fecha edición')),
                ('hash_archivo', models.IntegerField(default=None)),
                ('propietario', models.ForeignKey(help_text='Miembro del equipo de trabajo responsable del Archivo', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('reemplaza_a', models.ForeignKey(blank=True, default=None, help_text='Archivo al cual revisiona', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='archivo_reemplaza_a', to='documental.Archivo')),
                ('reemplazado_por', models.ForeignKey(blank=True, default=None, help_text='Archivo por el cual es revisionado', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='archivo_reemplazado_por', to='documental.Archivo')),
            ],
            options={
                'ordering': ['nombre_archivo', 'revision'],
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden_trabajo', models.CharField(help_text='Nro. Orden de Trabajo', max_length=50)),
                ('fecha', models.DateField(default=django.utils.timezone.now, help_text='Fecha de Inicio del Trabajo')),
                ('descripcion', models.CharField(help_text='Breve descripción del Trabajo', max_length=1000, null=True, verbose_name='Descripción')),
                ('finalizado', models.BooleanField(default=False, help_text='Estado de finalización del Trabajo')),
                ('directorio', models.CharField(help_text='Ubicación (Carpeta) del Trabajo', max_length=255)),
                ('miembros', models.ManyToManyField(help_text='Miembros del equipo de Proyecto', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['fecha', 'orden_trabajo'],
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text='Nombre (Número) del Documento', max_length=255, verbose_name='Número')),
                ('fecha', models.DateField(default=django.utils.timezone.now, help_text='Fecha representativa para el Documento. Puede ser fecha de creación, por ejemplo')),
                ('tipo_documento', models.CharField(help_text='Tipo de Documento (Plano, Informe, etc)', max_length=255, null=True)),
                ('tipo_obra', models.CharField(help_text='Tipo de obra que representa el Documento (Civil, Mecánico, etc)', max_length=255, null=True)),
                ('revision', models.CharField(default='A', help_text='Revisión actual del Documento', max_length=3, verbose_name='Revisión')),
                ('descripcion', models.CharField(help_text='Breve descripción del Documento', max_length=1000, null=True, verbose_name='Descripción')),
                ('compuesto_por', models.ManyToManyField(help_text='Archivos que componen el Documento', related_name='documento_compuesto_por', to='documental.Archivo')),
                ('propietario', models.ForeignKey(help_text='Miembro del equipo de trabajo responsable del Documento', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(help_text='Proyecto al que pertenece el Documento', null=True, on_delete=django.db.models.deletion.SET_NULL, to='documental.Proyecto')),
                ('reemplaza_a', models.ForeignKey(blank=True, default=None, help_text='Documento al cual revisiona', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documento_reemplaza_a', to='documental.Documento')),
                ('reemplazado_por', models.ForeignKey(blank=True, default=None, help_text='Documento por el cual es revisionado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documento_reemplazado_por', to='documental.Documento')),
                ('refiere_a', models.ManyToManyField(help_text='Documentos a los que hace referencia éste', related_name='_documento_refiere_a_+', to='documental.Documento')),
            ],
            options={
                'ordering': ['numero', 'revision'],
            },
        ),
        migrations.AddIndex(
            model_name='proyecto',
            index=models.Index(fields=['orden_trabajo', 'fecha'], name='documental__orden_t_a853ed_idx'),
        ),
        migrations.AddIndex(
            model_name='documento',
            index=models.Index(fields=['numero', 'revision'], name='documental__numero_ede602_idx'),
        ),
        migrations.AddIndex(
            model_name='archivo',
            index=models.Index(fields=['nombre_archivo', 'revision'], name='documental__nombre__987056_idx'),
        ),
    ]
