# Generated by Django 3.0.7 on 2020-06-19 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documental', '0002_auto_20200619_1606'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyecto',
            options={'ordering': ['fecha', 'orden_trabajo'], 'permissions': (('list_proyectos', 'Can list proyectos'), ('end_proyecto', 'Can finalize proyecto'))},
        ),
    ]
