# Generated by Django 3.0.7 on 2020-06-24 22:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('documental', '0004_auto_20200619_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='directorio',
            field=models.FilePathField(help_text='Directorio de almacenamiento del archivo', max_length=1000, path='.'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='compuesto_por',
            field=models.ManyToManyField(blank=True, help_text='Archivos que componen el Documento', null=True, related_name='documento_compuesto_por', to='documental.Archivo'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now, help_text='Fecha representativa para el Documento'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='refiere_a',
            field=models.ManyToManyField(blank=True, help_text='Documentos a los que hace referencia este Documento', null=True, related_name='_documento_refiere_a_+', to='documental.Documento'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='directorio',
            field=models.CharField(help_text='Ubicación (Carpeta) del Trabajo', max_length=1000),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now, help_text='Fecha de inicio del Trabajo'),
        ),
    ]
