# Generated by Django 3.0.7 on 2020-06-24 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documental', '0006_auto_20200624_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='compuesto_por',
            field=models.ManyToManyField(blank=True, help_text='Archivos que componen el Documento', related_name='documento_compuesto_por', to='documental.Archivo'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='refiere_a',
            field=models.ManyToManyField(blank=True, help_text='Documentos a los que hace referencia este Documento', related_name='_documento_refiere_a_+', to='documental.Documento'),
        ),
    ]
