# Generated by Django 3.0.7 on 2020-06-26 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documental', '0008_documento_titulo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archivo',
            options={'ordering': ['nombre_archivo', 'revision'], 'permissions': (('revision_archivo', 'Add a revision to Archivo'),)},
        ),
        migrations.AlterModelOptions(
            name='documento',
            options={'ordering': ['numero', 'revision'], 'permissions': (('list_documentos', 'Can list documentos'), ('revision_documento', 'Add revision to Document'))},
        ),
        migrations.AlterField(
            model_name='archivo',
            name='tipo_representacion',
            field=models.CharField(help_text='Tipo de de representación del archivo (Planta, Modelo, Vista, etc)', max_length=255, null=True, verbose_name='Tipo de representación'),
        ),
    ]
