# Generated by Django 3.0.7 on 2020-06-26 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documental', '0009_auto_20200626_1126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archivo',
            options={'ordering': ['nombre_archivo', 'revision'], 'permissions': (('list_archivos', 'Can list Archivos'), ('revision_archivo', 'Add a revision to Archivo'))},
        ),
    ]
