# Generated by Django 3.0.7 on 2020-06-26 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documental', '0011_auto_20200626_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivo',
            name='proyecto',
            field=models.ForeignKey(blank=True, help_text='Proyecto al que pertenece el Archivo', null=True, on_delete=django.db.models.deletion.SET_NULL, to='documental.Proyecto'),
        ),
    ]
