# Generated by Django 3.0.7 on 2020-06-26 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documental', '0012_archivo_proyecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='hash_archivo',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
