# Generated by Django 3.0.7 on 2020-06-27 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documental', '0013_auto_20200626_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='nombre_archivo',
            field=models.FileField(help_text='Nombre del archivo', upload_to=''),
        ),
        migrations.AlterField(
            model_name='documento',
            name='compuesto_por',
            field=models.ManyToManyField(blank=True, help_text='Archivos que componen el Documento', related_name='archivos', to='documental.Archivo'),
        ),
    ]
