# Generated by Django 3.0.7 on 2020-06-27 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documental', '0014_auto_20200627_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='nombre_archivo',
            field=models.CharField(help_text='Nombre del archivo', max_length=255),
        ),
    ]
