# Generated by Django 3.0.7 on 2020-07-03 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documental', '0015_auto_20200627_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivo',
            name='reemplazado_por',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='reemplazado_por',
        ),
        migrations.AlterField(
            model_name='archivo',
            name='proyecto',
            field=models.ForeignKey(blank=True, help_text='Proyecto al que pertenece el Archivo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archivos_proyecto', to='documental.Proyecto'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='proyecto',
            field=models.ForeignKey(blank=True, help_text='Proyecto al que pertenece el Documento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_proyecto', to='documental.Proyecto'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='refiere_a',
            field=models.ManyToManyField(blank=True, help_text='Documentos a los que hace referencia este Documento', related_name='documentos_refiere_a', to='documental.Documento'),
        ),
    ]
