# Generated by Django 3.0.7 on 2020-07-03 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documental', '0016_auto_20200703_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='reemplaza_a',
            field=models.ForeignKey(blank=True, default=None, help_text='Archivo al cual revisiona', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='archivo_reemplazado_por', to='documental.Archivo'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='reemplaza_a',
            field=models.ForeignKey(blank=True, default=None, help_text='Documento al cual revisiona', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documento_reemplazado_por', to='documental.Documento'),
        ),
    ]
