# Generated by Django 3.0.7 on 2020-07-07 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espacial', '0002_auto_20200707_1129'),
        ('documental', '0017_auto_20200703_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivo',
            name='espacial',
            field=models.ManyToManyField(blank=True, help_text='Ubicación espacial del archivo', related_name='espacialesfile', to='espacial.ElementoEspacial'),
        ),
        migrations.AddField(
            model_name='documento',
            name='espacial',
            field=models.ManyToManyField(blank=True, help_text='Ubicación espacial del documento', related_name='espacialesdoc', to='espacial.ElementoEspacial'),
        ),
    ]
