# Generated by Django 3.0.7 on 2020-07-29 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajes', '0001_initial'),
        ('documental', '0018_auto_20200707_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivo',
            name='mensaje',
            field=models.ManyToManyField(blank=True, help_text='Mensajes de actividad sobre el documento', related_name='mensajesarch', to='mensajes.Mensaje'),
        ),
        migrations.AddField(
            model_name='archivo',
            name='tique',
            field=models.ManyToManyField(blank=True, help_text='Mensajes de actividad sobre el documento', related_name='tiquesarch', to='mensajes.Tique'),
        ),
        migrations.AddField(
            model_name='documento',
            name='mensaje',
            field=models.ManyToManyField(blank=True, help_text='Mensajes de actividad sobre el documento', related_name='mensajesdoc', to='mensajes.Mensaje'),
        ),
        migrations.AddField(
            model_name='documento',
            name='tique',
            field=models.ManyToManyField(blank=True, help_text='Mensajes de actividad sobre el documento', related_name='tiquesdoc', to='mensajes.Tique'),
        ),
    ]
